name: Python application

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install Poetry and codecov
        run: |
          pip install poetry codecov
      - name: Install dependencies
        run: poetry install
      - name: Run tests with coverage
        run: |
          poetry run coverage run -m pytest -v
      - name: Upload coverage to Codecov
        run: codecov

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install Poetry
        run: pip install poetry
      - name: Configure Poetry with PyPI token
        run: |
          poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"
      - name: Build and publish to PyPI
        run: |
          poetry build
          poetry publish --no-interaction --build
