name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["10", "12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache yarn
        uses: actions/cache@v4
        with:
          path: ~/.yarn-cache
          key: ${{ runner.os }}-yarn-cache
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Integration test
        run: yarn test:integration
      - name: Notelemetry test
        run: yarn test:notelemetry
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn coveralls