name: Node.js Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12', '14', '16']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Install Firefox
        run: |
          curl -sS -o /tmp/firefox.tar.gz https://download.mozilla.org/?product=firefox-latest-ssl&os=linux&lang=en-US
          tar -xvf /tmp/firefox.tar.gz -C /usr/local
      - name: Install Playwright
        run: npx playwright install
      - name: Build
        run: npm run build