name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      QT_QPA_PLATFORM: "offscreen"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install graphviz graphviz-dev
          pip install -U setuptools
          pip install pytest codecov pytest-cov
      - name: Install package
        run: |
          pip install ".[full,test]"
      - name: Run tests
        run: |
          pytest --rootdir=$GITHUB_WORKSPACE --cov=.
      - name: Code coverage
        uses: codecov/codecov-action@v2