name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install graphviz
      run: |
        sudo apt-get install graphviz-dev
        pip install pygraphviz

    - name: Install dependencies
      run: pip install pytest codecov pytest-cov

    - name: Test with pytest and coverage
      run: |
        export QT_QPA_PLATFORM="offscreen"
        pytest --rootdir ${{ github.workspace }} --cov=./

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1