name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Yarn
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
          export PATH=$HOME/.yarn/bin:$PATH
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache Yarn
        uses: actions/cache@v4
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-cache
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test

    environment:
      NODEJS_VERSION: "18"